-- 코드를 입력하세요
# SELECT AS HOUR, COUNT(*) AS COUNT
SELECT
(CASE 
 WHEN DATE_FORMAT(DATETIME, '%H') = '09' THEN '9'
 ELSE DATE_FORMAT(DATETIME, '%H')
END) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H:%i') BETWEEN '09:00' AND '19:59'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H')